### ISSUE TITLE
Something Wrong with Math Expression on iPad Chrome

### ISSUE THREAD

**Issue by luc1fev** [gera2ld/markmap#112] opened 2022-05-09 12:14 UTC
![Screenshot 2022-05-09 at 5 09 21 AM](https://user-images.githubusercontent.com/10078186/167407593-2eface58-7dd0-4d64-b53d-2edb8770a513.png)
The location of the expression is incorrect

**Comment by gera2ld** [comment] 2022-05-10 05:28
duplicate of #15

**Closed by gera2ld** 2022-05-10 05:28 UTC
