### ISSUE TITLE
Markdown **BOLD** is not visible in preview. 

### ISSUE THREAD

**Issue by ChrisFab16** [gera2ld/markmap#78] opened 2021-05-20 12:27 UTC
PhiLhoSoft suggested a fix:

Technically, it is not Markdown grammar, it is HTML, and an obsolete one! (`<font>` hand been deprecated for a long time).
Apparently, simple Markdown is supported, as show in the playground: `**inline** ~~text~~ *styles*` --> **inline** ~~text~~ *styles*

One note, though, to @gera2ld: you style the `<strong>` tag with a `font-weight: bolder;` style, but it goes from 300 to 400, and the difference is not visible, at least on Firefox and Chrome in Windows.
I suggest to use a simple `font-weight: bold;` instead.

_Originally posted by @PhiLhoSoft in https://github.com/gera2ld/markmap/issues/26#issuecomment-700250367_

**Comment by gera2ld** [comment] 2021-05-20 13:07
Duplicate of #27.
The problem is, `bold` does not look that good in default fonts (macOS, Windows).

Some popular examples: [normalize.css](https://necolas.github.io/normalize.css/) styles `font-weight: bolder` for `<strong>`, GitHub styles `font-weight: 600` for `<strong>`.

Anyway you can override the styles by the `style` option.

**Closed by gera2ld** 2021-05-20 13:07 UTC

**Comment by ChrisFab16** [comment] 2021-05-20 14:22
> Anyway you can override the styles by the `style` option.
How would I do this for the VScode plugin?

Do I add a <style> element in the markdown document? Or is there a config option in markmap?

I can't see anything in the documentation here: https://markmap.js.org/docs/

**Comment by gera2ld** [comment] 2021-05-20 15:08
Sorry, my bad, the options have not been documented yet.
If you are using the API, you can add custom style like this:

```js
Markmap.create(el, {
  style: id => `.${id}-fo strong { font-weight: bold }`,
});
```

There is no way to change style in the VSCode extension yet. But there is a plan to read options from the Markdown front-matter.
